#!/usr/bin/env python3
"""Regenerate deterministic GoldAtom/0 simulation vectors and Markdown."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from goldatom.demo import build_simulated_fixture
from goldatom.protocol import build_work_header
from goldatom.verify import verify_bundle


def main() -> int:
    genesis = build_simulated_fixture()
    transferred = build_simulated_fixture(with_transfer=True)
    genesis.bundle.write(ROOT / "examples" / "genesis.goldatom.json")
    transferred.bundle.write(ROOT / "examples" / "transferred.goldatom.json")
    report = verify_bundle(genesis.bundle, genesis.view)
    transfer_report = verify_bundle(transferred.bundle, transferred.view)
    work_header = build_work_header(
        challenge_digest=bytes.fromhex(genesis.bundle.work.challenge_digest_hex),
        claim_commitment_digest=bytes.fromhex(genesis.bundle.claim.commitment_hex),
        extra_nonce=genesis.bundle.work.extra_nonce,
        nonce=genesis.bundle.work.nonce,
    )
    text = f"""# GoldAtom/0 Deterministic Test Vectors

Generated by `scripts/generate_test_vectors.py` from the normative Python implementation.

## Genesis simulation vector

| Field | Value |
|---|---|
| Profile | `{genesis.bundle.profile}` |
| Claim txid | `{genesis.bundle.claim.outpoint.txid}` |
| Claim vout | `{genesis.bundle.claim.outpoint.vout}` |
| Claim block | `{genesis.bundle.claim.block_hash}` |
| Claim height | `{genesis.bundle.claim.height}` |
| Claim commitment | `{genesis.bundle.claim.commitment_hex}` |
| Challenge block | `{genesis.bundle.work.challenge_block_hash}` |
| Challenge height | `{genesis.bundle.work.challenge_height}` |
| Challenge digest | `{genesis.bundle.work.challenge_digest_hex}` |
| Extra nonce | `{genesis.bundle.work.extra_nonce}` |
| Nonce | `{genesis.bundle.work.nonce}` |
| Target | `{genesis.bundle.claim.target_hex}` |
| Work hash | `{genesis.bundle.work.work_hash_hex}` |
| Mint txid | `{genesis.bundle.mint.txid}` |
| Mint block | `{genesis.bundle.mint.block_hash}` |
| Mint height | `{genesis.bundle.mint.height}` |
| Mint commitment | `{genesis.bundle.mint.commitment_hex}` |
| Atom ID | `{report.atom_id}` |
| Current title | `{report.current_title_outpoint}` |
| Expected local hashes | `{report.expected_local_hashes}` |
| Burial blocks at vector tip | `{report.burial_blocks}` |
| Burial chainwork at vector tip | `{report.burial_chainwork}` |

## Exact 80-byte work header

```text
{work_header.hex()}
```

Length: `{len(work_header)}` bytes.

Split by field:

```text
magic              {work_header[0:4].hex()}
challenge_digest   {work_header[4:36].hex()}
claim_commitment   {work_header[36:68].hex()}
extra_nonce_le     {work_header[68:72].hex()}
reserved           {work_header[72:76].hex()}
nonce_le           {work_header[76:80].hex()}
```

Double SHA-256:

```text
SHA256d(work_header) = {genesis.bundle.work.work_hash_hex}
```

The raw digest is interpreted as a big-endian integer and is below the committed target.

## One-transfer vector

| Field | Value |
|---|---|
| Atom ID | `{transfer_report.atom_id}` |
| Transfer count | `{transfer_report.title_transfers}` |
| Terminal title | `{transfer_report.current_title_outpoint}` |
| Assay tip height | `{transfer_report.as_of_tip_height}` |
| Burial blocks | `{transfer_report.burial_blocks}` |
| Burial chainwork | `{transfer_report.burial_chainwork}` |
| Transfer txid | `{transferred.bundle.transfers[0].txid}` |
| Transfer commitment | `{transferred.bundle.transfers[0].commitment_hex}` |

The Atom ID remains unchanged across title transfer; only the terminal title outpoint changes.

## Regeneration

```bash
python3 scripts/generate_test_vectors.py
python3 -m unittest discover -s tests -v
```
"""
    (ROOT / "TEST-VECTORS.md").write_text(text, encoding="utf-8")
    print("Regenerated examples/genesis.goldatom.json")
    print("Regenerated examples/transferred.goldatom.json")
    print("Regenerated TEST-VECTORS.md")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
